apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdvdemo
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: frontend-service
            port:
              number: 80
        path: /
        pathType: Prefix