apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: sdvdemo
spec:
  ports:
    - port: 3306
  selector:
    app: sdvdemo
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sdvdemo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdvdemo-mysql
  labels:
    app: sdvdemo
spec:
  selector:
    matchLabels:
      app: sdvdemo
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sdvdemo
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Sommer123456"
        - name: MYSQL_DATABASE
          value: sdvdemodatabase
        - name: MYSQL_USER
          value: markusfelsner
        - name: MYSQL_PASSWORD
          value: "Sommer123456"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
