apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: sdvdemo
spec:
  ports:
    - port: 3306
  selector:
    app: sdvdemo
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sdvdemo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sdvdemo-mysql
  labels:
    app: sdvdemo
spec:
  serviceName: mysql-service
  selector:
    matchLabels:
      app: sdvdemo
      tier: mysql
  template:
    metadata:
      labels:
        app: sdvdemo
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sdvdemo-config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
              configMapKeyRef:
                name: sdvdemo-config
                key: MYSQL_DATABASE          
        - name: MYSQL_USER
          valueFrom:
              configMapKeyRef:
                name: sdvdemo-config
                key: MYSQL_USER          
        - name: MYSQL_PASSWORD
          valueFrom:
              configMapKeyRef:
                name: sdvdemo-config
                key: MYSQL_PASSWORD
        - name: MYSQL_DBHOST
          valueFrom:
                configMapKeyRef:
                  name: sdvdemo-config
                  key: MYSQL_DBHOST
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
