apiVersion: v1
kind: ConfigMap
metadata:
  name: sdvdemo-config
data:
  MYSQL_ROOT_PASSWORD: Sommer123456
  MYSQL_DATABASE: sdvdemodatabase
  MYSQL_USER: markusfelsner
  MYSQL_PASSWORD: Sommer123456
  MYSQL_DBHOST: mysql-service
  